/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:c4606d0a-d246-4c80-b805-f256fe0b9f49",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_5jEQlDVCP",
    "aws_user_pools_web_client_id": "1nbej6vg87oaq0gl4d6o2q1qed",
    "oauth": {}
};


export default awsmobile;
